name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ghcr.io/whywelive/330-actions/students-node-330:latest ./node/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push ghcr.io/whywelive/330-actions/students-node-330:latest

      - name: send telegram message on push (success)
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: 979715547
          token: 7243039707:AAHh4Y_9AFL7OOnN2nkz3xYRUxQsXYzwVL8
          message: |
            Успешно запушили образ.

      - name: send telegram message on push (failure)
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: 979715547
          token: 7243039707:AAHh4Y_9AFL7OOnN2nkz3xYRUxQsXYzwVL8
          message: |
            not Успешно запушили образ.


